server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb?MODE=MYSQL}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha

gemini:
  api-key: ${GEMINI_API_KEY}
  model: ${GEMINI_MODEL:gemini-1.5-flash}