spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: true
      path: /h2-console