name: Docs Build & Deploy

on:
  push:
    branches: [ develop, feat/#52 ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci
        working-directory: docs

      - name: Build VitePress site
        run: npm run docs:build
        working-directory: docs

      - name: Publish to gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: docs
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --cwd docs/.vitepress/dist
